name: DockerHub + Kubernetes Demo

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: node-app
  CONTAINER_PORT: 3000

jobs:
  k8s-demo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:latest .

      - name: Push image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:latest

      - name: Install kubectl
        run: |
          curl -LO https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Install kind
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.22.0/kind-linux-amd64
          chmod +x kind
          sudo mv kind /usr/local/bin/kind

      - name: Create Kubernetes cluster
        run: |
          kind create cluster --name demo-cluster

      - name: Deploy app to Kubernetes
        run: |
          kubectl create deployment node-app \
            --image=${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:latest

          kubectl expose deployment node-app \
            --type=NodePort \
            --port=$CONTAINER_PORT

      - name: Wait for pods
        run: |
          kubectl rollout status deployment/node-app

      - name: Check resources
        run: |
          kubectl get pods
          kubectl get svc

      - name: Test application
        run: |
          kubectl port-forward deployment/node-app 8080:3000 &
          sleep 5
          curl http://localhost:8080

      - name: Cleanup Kubernetes resources
        run: |
          kubectl delete svc node-app
          kubectl delete deployment node-app
          kind delete cluster --name demo-cluster
